#define SSI "YOUR WIFI NAME HERE"
#define WIFI_PASSWORD "YOUR WIFI PASSWORD HERE"
#define MQTT_U "YOUR MQTT USERNAME HERE"
#define MQTT_P "YOUR MQTT PASSWORD HERE"
#define RPI_IP "YOUR MQTT BROKER IP ADDRESS HERE"
#define MQTT_PRT YOUR MQTT PORT NUMBER, default is 1883; 
#define LIGHT "YOUR NAME FOR YOUR LED CONTROLLER HERE" 
#define OTApass "YOUR PASSWORD FOR WIRELESS CODE UPLOAD TO THE CONTROLLER" 